[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "code_chart"
version = "0.2.0"
authors = [
    { name = "keonghun, choi" },
]
description = "Code Hierarchy & Architecture Rendering Tool"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "libclang",
    "python_toolbox @ git+https://github.com/DXR-keonghun6612/ToolBox.git@python_toolbox",
]

[project.scripts]
pychart = "pychart.printer:Cli_Main"
cchart = "cchart.printer:Cli_Main"

[tool.setuptools.packages.find]
include = ["core*", "pychart*", "cchart*"]
