task: classification
unit: object
ratios:
    train: 0.9
    val: 0.1
    test: 0.0
salt: ''
processes:
-   object_type: attr_gate
    key: obj_id
    keep: ['0']
    max: null
    min: null
    missing: skip
-   object_type: center_distance
    max_dist: 0.2
-   object_type: normalize_mask
    target_shape: 256
    scale: 255
    slots:
        mask: crop
