flows:
-   object_type: flow
    name: extract_raw_obj_by_edge
    unit: frame
    processes:
    -   object_type: detect_edge
        low: 50
        high: 150
        blur: 3
        gray: false
        outputs:
            edge:
                to: storage
                level: frame
                format: png
    -   object_type: close_edge
        size: 21
        outputs:
            edge:
                to: storage
                level: frame
                format: png
                dir: close_edge
    -   object_type: fill_edge
        min_area: 500
        border_gap: 50
        outputs:
            mask:
                to: storage
                level: frame
                format: png
                dir: fill_edge
    -   object_type: morph_mask
        close_size: 3
        open_size: 3
        reverse: false
        outputs:
            mask:
                to: storage
                level: frame
                format: png
                dir: morph_mask
    -   object_type: split_objects
        min_area: 500
        mask_reverse: false
        merge_gap: 0
        bbox_gap: 0.15
        outputs:
            object: {}
            segment:
                to: storage
                level: frame
                type: segmap
                format: png
                dir: raw_mask
