flows:
-   object_type: flow
    name: Extract_mask_by_detection
    unit: frame
    processes:
    -   object_type: detect_instances
        threshold: 0.5
        min_area: 400
        merge_gap: 0
        bbox_gap: 0.0
        model:
            type: onnx_seg
            onnx_file: detection_FP32.onnx
            cfg_file: detection_FP32_rt_cfg.yaml
            device_id: 0
        outputs:
            object: {}
    -   object_type: filter_by_roi
        outputs:
            object: {}
    -   object_type: order_objects
        outputs:
            object: {}
